services:
  lb:
    build: .
    command: ["org.lb4.loadbalancer.Main", "/app/config.yaml"]
    ports:
      - "8080:8080"
    depends_on:
      - backend1
      - backend2
      - backend3

  backend1:
    build: .
    command: ["org.lb4.loadbalancer.tools.TcpEchoServer", "9001", "backend-1"]
    ports:
      - "9001:9001"

  backend2:
    build: .
    command: ["org.lb4.loadbalancer.tools.TcpEchoServer", "9002", "backend-2"]
    ports:
      - "9002:9002"

  backend3:
    build: .
    command: ["org.lb4.loadbalancer.tools.TcpEchoServer", "9003", "backend-3"]
    ports:
      - "9003:9003"