server:
  listen_ip: 0.0.0.0
  listen_port: 8080

load_balancing:
  algorithm: ip_hash   # or round_robin

backends:
  - id: backend-1
    host: backend1
    port: 9001
  - id: backend-2
    host: backend2
    port: 9002
  - id: backend-3
    host: backend3
    port: 9003